# Generated by Django 6.0.3 on 2026-05-04 09:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('bank_name', models.CharField(max_length=120, verbose_name='اسم البنك')),
                ('account_name', models.CharField(max_length=120, verbose_name='اسم الحساب')),
                ('account_number', models.CharField(max_length=80, verbose_name='رقم الحساب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
                'ordering': ['bank_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company_name', models.CharField(default='نظام متابعة المحافظ الإلكترونية', max_length=160, verbose_name='اسم الشركة')),
                ('company_logo', models.FileField(blank=True, upload_to='settings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='شعار الشركة')),
                ('default_currency', models.CharField(default='جنيه', max_length=30, verbose_name='العملة الافتراضية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=120, verbose_name='اسم المحفظة')),
                ('wallet_type', models.CharField(choices=[('vodafone_cash', 'Vodafone Cash'), ('orange_cash', 'Orange Cash'), ('instapay', 'InstaPay'), ('other', 'أخرى')], max_length=40, verbose_name='نوع المحفظة')),
                ('phone_number', models.CharField(max_length=30, verbose_name='رقم المحفظة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرصيد الافتتاحي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'محفظة',
                'verbose_name_plural': 'المحافظ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('transaction_type', models.CharField(choices=[('customer_payment', 'وارد من عميل'), ('wallet_to_bank', 'تحويل إلى البنك')], default='customer_payment', max_length=30, verbose_name='نوع العملية')),
                ('customer_name', models.CharField(blank=True, max_length=120, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='رقم العميل')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='العمولة')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='الصافي')),
                ('reference_number', models.CharField(blank=True, max_length=120, verbose_name='رقم العملية')),
                ('transaction_date', models.DateTimeField(verbose_name='تاريخ العملية')),
                ('receipt_image', models.FileField(blank=True, upload_to='receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='صورة الإيصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.bankaccount', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='أضيفت بواسطة')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'عملية',
                'verbose_name_plural': 'العمليات',
                'ordering': ['-transaction_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_number', ''), _negated=True), fields=('reference_number',), name='unique_non_empty_reference_number')],
            },
        ),
    ]
